# cython_add_module( <name> src1 src2 ... srcN )
# Build the Cython Python module.
function(cython_add_module _name pyx_target_name generated_files)
  set(pyx_module_source "")
  set(other_module_sources "")
  foreach(_file ${ARGN})
    if(${_file} MATCHES ".*\\.py[x]?$")
      list(APPEND pyx_module_source ${_file})
    else()
      list(APPEND other_module_sources ${_file})
    endif()
  endforeach()
  compile_pyx(${_name} ${pyx_target_name} _generated_files ${pyx_module_source})
  set(${generated_files} ${_generated_files} PARENT_SCOPE)
  include_directories(${PYTHON_INCLUDE_DIRS})
  python_add_module(${_name} ${_generated_files} ${other_module_sources})
  add_dependencies(${_name} ${pyx_target_name})
endfunction()
